Initial commit
krogenth/AdditionalPylons pull request #21
Opened 2022-02-01 20:32 UTC by Soulsteeler123

Skeleton of Player class

2022-02-05 06:07 UTC, 0x416C657852 requested changes
lgtm,
just change that thing, yknow the thing from earlier I already forgot about. p sure I commented it somewhere

2022-02-05 06:07 UTC, 0x416C657852 commented on src/AdditionalPylonsModule.cpp
>  void AdditionalPylonsModule::onUnitDestroy(BWAPI::Unit unit) {
😿onUnitCreate on delete.

2022-02-05 19:27 UTC, krogenth commented on src/Players/Player.cpp
> +	BWAPI::Broodwar->drawTextScreen(x, y, "# of units that %s control: %s", ourRace.toString(), std::to_string(buildings.size()));
- `std::to_string(units.size())` should just be `units.size()`, you can use `%d` for outputting integer values
- `ourRace.toString()` won't work, instead, we'll have to check the value stored and create a string off of that(or just output the numerical value stored in the race object)
- the current setup will overlap text on the screen, which we don't want to have happen, preferably, we want as little width used as possible

2022-02-05 19:27 UTC, krogenth commented on src/Players/Player.cpp
> +	BWAPI::Broodwar->drawTextScreen(x, y, "This player's race is: %s", ourRace.toString());
This method isn't very useful, since `DisplayInfo` also outputs the race

2022-02-05 19:27 UTC, krogenth commented on src/Players/Player.cpp
> +	//enemyRace = BWAPI::Races::Unknown;
remove dead code

2022-02-05 19:27 UTC, krogenth commented on vs/AdditionalPylons/AdditionalPylons.vcxproj.filters
> +    <ClCompile Include="..\..\src\Players\Player.cpp">
Fix vs project filters, they should replicate the storage folder structure

2022-02-08 22:14 UTC, krogenth approved these changes

2022-02-14 03:13 UTC, 0x416C657852 approved these changes

2022-02-14 03:18 UTC, merged